# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebf6b495069693a6bd6afa4f563f5d2d8ecf75d4e441cd5486ede58e14f0fc8b9a6c471c1fb4da952e5cc631c157fbdcee4ea081e6ae70594992916abc7ca080

test:
  secret_key_base: e527d4932b7bd34aacfc08ca692eb1783cad7ccded9e471a06b5d5456ec0523656c2d72fa43abff255f90f1731c968c31dd15e9d400b4735bd6aac45054ff17d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
